<?php

/**
 * @file kalturakaf.module
 * This file includes general module hooks implementations
 */
module_load_include('php', 'kalturakaf', 'kalturaClient/KalturaClient');
define('KALTURAKAF_NOT_INITIALIZED_ERR', 'Kaltura KAF module is not initialized. Complete the module configuration first in ');


/**
 * Implements hook_menu().
 */
function kalturakaf_menu() {
  $items['admin/config/media/kalturakaf'] = array(
    'title' => 'Kaltura-KAF module settings',
    'file' => 'kalturakaf_admin.php',
    'description' => t('Check on the server integration status with Kaltura, import entries from Kaltura, see existing media and edit metadata and additional configuration options.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kalturakaf_setup_form'),
    'access arguments' => array('administer site configuration'),
    'weight' => -10,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * helper function to check if the module is properly configured
 * 
 * @return boolean
 */
function kalturakaf_is_initialized()
{
    if(!variable_get('kalturakaf_partner_id'))
    {
        return false;
    }
    
    if(!variable_get('kalturakaf_admin_secret'))
    {
        return false;
    }
    
    if(!variable_get('kalturakaf_url'))
    {
        return false;
    }
    
    return true;
}

/**
 * helper function to generate a KS and attach it to the KAF page URL.
 * the result should be used as the iFrame SRC
 * 
 * @param string $uri
 * @param array $privileges
 * @param boolean $isAbsolute
 * @return string
 * @throws Exception
 */
function kalturakaf_get_frame_src($uri, $privileges, $isAbsolute = false)
{
    // get the current user ID for the KS
    $userId = kalturakaf_get_username();
    
    // verify module is configured
    if(!kalturakaf_is_initialized()) {
        $adminLink = l('admin/config/media/kalturakaf');
        throw new Exception(KALTURAKAF_NOT_INITIALIZED_ERR . $adminLink);
    }
    
    // verify we recieved privileges - we can't work without specific privileges per KAF page
    if(!is_array($privileges)) {
        throw new Exception("KAF frame src privileges must be an array");
    }
    
    // get required parameters
    $config = new KalturaConfiguration(variable_get('kalturakaf_partner_id'));
    $client = new KalturaClient($config);
    
    // add actionsLimit privilege with -1 to make sure KS can't be used to perform API calls to Kaltura
    if(!isset($privileges['actionslimit'])) {
        $privileges['actionslimit'] = -1;
    }
    
    // bulild privileges as string
    $privStr = '';
    foreach($privileges as $priv => $value) {
        $privStr .= $priv . ":" . $value . ",";
    }
    
    // generate the KS
    $ks = $client->generateSessionV2(variable_get('kalturakaf_admin_secret'), 
            $userId, 
            KalturaSessionType::USER, // forcing type USER so KS is weak
            variable_get('kalturakaf_partner_id'),
            60, // limiting to short expiry
            $privStr
    );
    
    if(!$isAbsolute)
    {
        // remove trailing slashes just in case, as it may break KAF friendly-URL structure
        rtrim($uri, '/');
        $url = variable_get('kalturakaf_url') . $uri . '/ks/' . $ks;
    }
    else
    {
        rtrim($uri, '/');
        $url = $uri . '/ks/' . $ks;
    }
    
    return $url;
}

/**
 * helper function to determine the name of the currently logged-in user
 * 
 * @global stdClass $user
 * @return string
 */
function kalturakaf_get_username()
{
    global $user;
    if($user->uid > 0)
    {
        $userId = $user->name;
    }
    else
    {
        $userId = '';
    }
    return $userId;
}